"""Registry -> problem folders on main: problem.md, main.py stubs, ✅ status.

The registries on OP are the source of truth; every problem.md is generated
from them, so it can be regenerated at will (render_problems.py) or right after
a scrape. Two kinds of file are never overwritten:

  * a problem.md without the generated marker (or the legacy heading) is
    hand-written, and
  * a main.py that is not an untouched stub is the student's work.

`recommended/` is authored content and is never written.
"""

from __future__ import annotations

import json
import os
import re
import sys
from dataclasses import dataclass, field
from typing import Any, Iterable, Mapping

from . import code, config, fsio, paths

GENERATED_MARKER = (
    "<!-- generated by .op/scripts/render_problems.py from "
    "data/all_problems_detail.json — edit the data, not this file -->"
)
# Heading every problem.md written by the old scraper carries.
LEGACY_HEADING = "## 1. โจทย์จริงจาก iJudge"

PASSED_SUFFIX = " ✅"

CATEGORY_LABELS = (
    ("is_learning_log", "Learning Log"),
    ("is_recommended", "Recommended"),
    ("is_midterm", "Midterm"),
    ("is_mini_exam", "Mini Exam"),
)


# ---------------------------------------------------------------------------
# statement text
# ---------------------------------------------------------------------------

# iJudge statements are markdown with raw HTML fragments mixed in. Ported from
# ihelp's build_pscp_registry.normalize_statement, plus the structural tags
# that would otherwise lose meaning when stripped: <pre> keeps its layout as a
# fence, <li> becomes a list item, <a> a markdown link.
_STRUCTURE_REWRITES = [
    (re.compile(r"<pre[^>]*>\n?", re.I), "\n```text\n"),
    (re.compile(r"\n?</pre>", re.I), "\n```\n"),
    (re.compile(r'<a\s[^>]*?href="([^"]*)"[^>]*>(.*?)</a>', re.I),
     lambda m: f"[{m.group(2) or m.group(1)}]({m.group(1)})"),
    (re.compile(r"^[ \t]*<li\b[^>]*>", re.I | re.M), "- "),
    (re.compile(r"<li\b[^>]*>", re.I), "\n- "),
]

def _emphasis(marker: str):
    """Rewrite a paired tag to markdown emphasis with the spaces moved out.

    `<b>บรรทัดที่ 1 : </b>` must become `**บรรทัดที่ 1 :** `: a closing
    `**` right after a space is not a closer, and the bold never ends.
    """
    def repl(m: re.Match[str]) -> str:
        inner = m.group(2)
        core = inner.strip()
        if not core:
            return inner
        lead = inner[: len(inner) - len(inner.lstrip())]
        trail = inner[len(inner.rstrip()):]
        return f"{lead}{marker}{core}{marker}{trail}"
    return repl


_TAG_REWRITES = [
    # `<br />` is usually followed by the source's own newline; together they
    # are one line break, not a paragraph break.
    (re.compile(r"<br\s*/?>[ \t]*\n?", re.I), "\n"),
    (re.compile(r"<(b|strong)>(.*?)</\1>", re.I | re.S), _emphasis("**")),
    (re.compile(r"<(i|em)>(.*?)</\1>", re.I | re.S), _emphasis("*")),
    (re.compile(r"</?(?:u|ins)>", re.I), ""),
    (re.compile(r"</?(?:b|strong)>", re.I), "**"),
    (re.compile(r"</?(?:i|em)>", re.I), "*"),
    (re.compile(r"</?(?:p|div|span|font)[^>]*>", re.I), ""),
]

# Decoded `<` and `>` go through placeholders so the escaping pass can tell
# them apart from HTML that is kept on purpose (<img>, <!-- -->).
_LT, _GT = "", ""
_ENTITIES = {
    "&nbsp;": " ", "&amp;": "&", "&lt;": _LT, "&gt;": _GT, "&quot;": '"',
    "&#39;": "'",
}

_FENCE_OPEN = re.compile(r"^ {0,3}(`{3,}|~{3,})")
_CODE_SPAN = re.compile(r"(?<!`)(`+)(?!`)(.+?)(?<!`)\1(?!`)")


def _split_fences(text: str) -> list[tuple[bool, list[str]]]:
    """Split markdown into (is_fenced_code, lines) runs.

    An unclosed fence runs to the end of the text, as in CommonMark.
    """
    runs: list[tuple[bool, list[str]]] = []
    current: list[str] = []
    fence: str | None = None
    for line in text.split("\n"):
        if fence is None:
            m = _FENCE_OPEN.match(line)
            if m:
                if current:
                    runs.append((False, current))
                current, fence = [line], m.group(1)
                continue
            current.append(line)
        else:
            current.append(line)
            stripped = line.strip()
            if stripped and set(stripped) == {fence[0]} and len(stripped) >= len(fence):
                runs.append((True, current))
                current, fence = [], None
    if current:
        runs.append((fence is not None, current))
    return runs


def _escape_prose(text: str, line_start: bool) -> str:
    """Escape what GitHub would misread in plain statement text."""
    # `$` starts LaTeX math on GitHub (problem 3362 prints `$` symbols).
    text = re.sub(r"(?<!\\)\$", r"\\$", text)
    # A decoded `<type>` would be swallowed as an unknown HTML tag.
    text = re.sub(_LT + r"(?=[A-Za-z/!?])", r"\\<", text)
    # A decoded `>` opening a line would start a block quote.
    if line_start:
        text = re.sub(r"^(\s*)" + _GT, r"\1\\>", text)
    return text.replace(_LT, "<").replace(_GT, ">")


def _escape_markdown(text: str) -> str:
    """Apply _escape_prose outside fenced code and inline code spans."""
    out: list[str] = []
    for fenced, lines in _split_fences(text):
        for line in lines:
            if fenced:
                out.append(line.replace(_LT, "<").replace(_GT, ">"))
                continue
            parts: list[str] = []
            last = 0
            for m in _CODE_SPAN.finditer(line):
                parts.append(_escape_prose(line[last:m.start()], last == 0))
                parts.append(m.group(0).replace(_LT, "<").replace(_GT, ">"))
                last = m.end()
            parts.append(_escape_prose(line[last:], last == 0))
            out.append("".join(parts))
    return "\n".join(out)


def normalize_statement(text: str | None) -> str:
    """iJudge statement HTML/markdown -> clean GitHub markdown.

    Unknown tags are dropped before entities are decoded: decoding first
    turns text such as `&lt; หรือ &lt;= หรือ &gt;` (3354) into something
    that looks like a tag and deletes it. Markdown image links are untouched.
    """
    if not text:
        return ""
    out = text.replace("\r\n", "\n").replace("\r", "\n")
    for pattern, repl in _STRUCTURE_REWRITES + _TAG_REWRITES:
        out = pattern.sub(repl, out)
    # Any tag we did not plan for is dropped rather than rendered literally.
    out = re.sub(r"<[^>\n]{1,40}>", "", out)
    for entity, repl in _ENTITIES.items():
        out = out.replace(entity, repl)
    # Collapse the runs of blank lines the <br /> expansion can leave behind.
    out = re.sub(r"\n{3,}", "\n\n", out)
    return _escape_markdown(out.strip())


def _hard_breaks(text: str) -> str:
    """Keep iJudge's line breaks when GitHub renders the text.

    iJudge shows every newline as a break (and `<br />` became one above);
    GitHub joins single newlines into one line. Two trailing spaces mark a
    hard break, and are simply dropped at the end of a block.
    """
    out: list[str] = []
    for fenced, lines in _split_fences(text):
        if fenced:
            out.extend(lines)
            continue
        lines = [line.rstrip() for line in lines]
        for i, line in enumerate(lines):
            following = lines[i + 1] if i + 1 < len(lines) else ""
            out.append(f"{line}  " if line and following else line)
    return "\n".join(out)


# ---------------------------------------------------------------------------
# problem.md
# ---------------------------------------------------------------------------

def _sample_text(value: Any) -> str:
    """Sample I/O exactly as judged: only line endings and outer blank lines.

    Leading spaces are kept, since pattern-drawing outputs depend on them.
    """
    if value is None:
        return ""
    text = str(value).replace("\r\n", "\n").replace("\r", "\n")
    return text.strip("\n")


def _sample_block(label: str, text: str, empty: str) -> list[str]:
    body = text.split("\n") if text.strip() else [empty]
    return [f"- **{label}**:", "  ```text", *(f"  {line}" for line in body), "  ```"]


def _week_line(item: Mapping[str, Any]) -> str | None:
    """'Week 10 · Learning Log' for the quote block, or None if unknown."""
    week = item.get("week")
    week_text = config.week_label(week) if week is not None else ""
    parts = [week_text] if week_text else []
    for flag, label in CATEGORY_LABELS:
        # "Week 7 / Midterm" already says Midterm.
        if item.get(flag) and label.lower() not in week_text.lower():
            parts.append(label)
    return " · ".join(parts) or None


def render_problem_md(detail: Mapping[str, Any], summary: Mapping[str, Any] | None) -> str:
    """problem.md for one detail record; `summary` supplies title, week, flags.

    The summary registry is preferred for those fields because a --fast scrape
    refreshes it without touching the detail records.
    """
    meta: Mapping[str, Any] = summary or detail
    cp = detail.get("courseProblem") or {}
    prob = detail.get("problem") or {}
    samples = detail.get("sampleCases") or []

    pid = detail.get("id") or cp.get("cp_id") or meta.get("id")
    raw_title = meta.get("name") or cp.get("cp_title") or prob.get("problem_title")
    title = config.clean_title(raw_title) or f"OJ {pid}"
    timeout = cp.get("cp_timeout") or 1
    memory_limit = cp.get("cp_memory_limit") or 32000
    lang = cp.get("cp_lang_type") or "Python"
    note = re.sub(r"\s*\n\s*", " ", normalize_statement(prob.get("problem_note")))

    def section(key: str) -> str:
        return _hard_breaks(normalize_statement(prob.get(key)))

    desc = section("problem_description")
    input_spec = section("problem_input_specification")
    output_spec = section("problem_output_specification")

    lines = [
        GENERATED_MARKER,
        f"# OJ {pid}: {title}",
        "",
        f"> - **iJudge cp_id**: {pid} — ภาษา {lang}",
        f"> - **เวลาจำกัด**: {timeout} วินาที | **หน่วยความจำ**: {memory_limit:,} KB",
    ]
    week_line = _week_line(meta)
    if week_line:
        lines.append(f"> - **สัปดาห์**: {week_line}")
    if note:
        lines.append(f"> - **โน้ตจากผู้ออกโจทย์**: {note}")
    lines += [
        "",
        "---",
        "",
        LEGACY_HEADING,
        "",
        desc or "*(ไม่มีคำอธิบายเพิ่มเติม)*",
        "",
        "## 2. Input Specification",
        "",
        input_spec or "*(ไม่มีข้อกำหนดอินพุต)*",
        "",
        "## 3. Output Specification",
        "",
        output_spec or "*(ไม่มีข้อกำหนดเอาต์พุต)*",
        "",
        "## 4. ตัวอย่างจาก iJudge",
        "",
    ]
    if samples:
        for idx, sample in enumerate(samples, 1):
            lines.append(f"### ตัวอย่างที่ {idx}")
            lines += _sample_block("อินพุต", _sample_text(sample.get("testcase_input")),
                                   "(ไม่มีอินพุต)")
            lines += _sample_block("เอาต์พุต", _sample_text(sample.get("testcase_output")),
                                   "(ไม่มีเอาต์พุต)")
            lines.append("")
    else:
        lines += ["*(ไม่มีตัวอย่าง Sample Testcase)*", ""]
    return "\n".join(lines).strip() + "\n"


def is_generated_md(text: str) -> bool:
    """True if a problem.md was written by a script and may be regenerated."""
    return GENERATED_MARKER in text or LEGACY_HEADING in text


def is_untouched_stub(text: str) -> bool:
    """Stricter code.is_stub: the marker alone does not make a file a stub.

    code.is_stub accepts any file containing STUB_MARKER, which would include
    a solution written underneath the marker comment. Before overwriting,
    require the file to still be a stub with the marker removed.
    """
    return code.is_stub(text) and code.is_stub(text.replace(code.STUB_MARKER, ""))


# ---------------------------------------------------------------------------
# folders
# ---------------------------------------------------------------------------

def _is_under(path: str, root: str) -> bool:
    return os.path.normpath(os.path.dirname(path)) == os.path.normpath(root)


def target_folder(item: Mapping[str, Any], index: Mapping[int, str] | None = None) -> str:
    """Folder of a problem on main: the existing one, else where a new one goes.

    `index` is a precomputed paths.index_problem_dirs() for batch callers.
    """
    pid = int(item["id"])
    existing = (index if index is not None else paths.index_problem_dirs()).get(pid)
    if existing:
        return existing
    if item.get("is_learning_log"):
        return os.path.join(paths.MAIN_ROOT, f"oj{pid}")
    name = config.folder_name(pid, item.get("name"))
    if item.get("status") == "Passed":
        name += PASSED_SUFFIX
    return os.path.join(paths.OJ_DIR, name)


def status_folder(item: Mapping[str, Any], folder: str) -> str:
    """Path `folder` should have for the problem's pass status.

    Only folders directly under oj/ carry the ✅ suffix; Learning Log folders
    at the root keep their name whatever the status.
    """
    if not _is_under(folder, paths.OJ_DIR):
        return folder
    base = re.sub(r"\s*✅$", "", os.path.basename(folder))
    if item.get("status") == "Passed":
        base += PASSED_SUFFIX
    return os.path.join(paths.OJ_DIR, base)


def sync_folder_status(item: Mapping[str, Any], folder: str) -> str:
    """Add or remove the ✅ suffix of an oj/ folder to match its status.

    Returns the folder's path afterwards: unchanged under --dry-run or when
    the rename is refused because the target exists.
    """
    desired = status_folder(item, folder)
    if desired == folder:
        return folder
    if fsio.rename_dir(folder, desired) and not fsio.is_dry_run():
        return desired
    return folder


# ---------------------------------------------------------------------------
# batch rendering, shared by render_problems.py and the scraper
# ---------------------------------------------------------------------------

@dataclass
class RenderStats:
    problem_md_written: int = 0
    folders_created: int = 0
    folders_renamed: int = 0
    stubs_created: int = 0
    stubs_refreshed: int = 0
    stubs_seeded: int = 0
    handwritten_skipped: list[int] = field(default_factory=list)
    no_detail: list[int] = field(default_factory=list)

    @property
    def changes(self) -> int:
        return (self.problem_md_written + self.folders_created + self.folders_renamed
                + self.stubs_created + self.stubs_refreshed + self.stubs_seeded)

    def report(self) -> str:
        lines = [
            f"problem.md written:    {self.problem_md_written}",
            f"folders created:       {self.folders_created}",
            f"folders renamed (✅):   {self.folders_renamed}",
            f"main.py stubs created: {self.stubs_created}",
            f"stubs refreshed:       {self.stubs_refreshed}",
            f"stubs seeded:          {self.stubs_seeded}",
            f"hand-written skipped:  {len(self.handwritten_skipped)}"
            + (f" ({', '.join(map(str, self.handwritten_skipped))})"
               if self.handwritten_skipped else ""),
        ]
        if self.no_detail:
            lines.append("no detail record (problem.md left alone): "
                         + ", ".join(map(str, self.no_detail)))
        return "\n".join(lines)


def load_registry(path: str) -> dict[int, dict[str, Any]]:
    """A registry JSON file as {id: record}; empty if it does not exist."""
    if not os.path.exists(path):
        return {}
    with open(path, "r", encoding="utf-8") as f:
        return {int(rec["id"]): rec for rec in json.load(f)}


def _read(path: str) -> str | None:
    if not os.path.exists(path):
        return None
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        return f.read()


def _render_main_py(item: Mapping[str, Any], detail: Mapping[str, Any] | None,
                    folder: str, seed_code: bool, stats: RenderStats) -> None:
    path = os.path.join(folder, "main.py")
    stub = code.stub_solution(config.clean_title(item.get("name")))
    seed = (detail or {}).get("beforeCode") if seed_code else None
    if not isinstance(seed, str) or not seed.strip():
        seed = None

    existing = _read(path)
    if existing is None:
        fsio.write_text(path, seed or stub)
        if seed:
            stats.stubs_seeded += 1
        else:
            stats.stubs_created += 1
        return
    if not is_untouched_stub(existing):
        return
    if seed and existing != seed:
        fsio.write_text(path, seed)
        stats.stubs_seeded += 1
    elif not seed and existing != stub:
        fsio.write_text(path, stub)
        stats.stubs_refreshed += 1


def render_problem(item: Mapping[str, Any], detail: Mapping[str, Any] | None,
                   *, seed_code: bool = False, stats: RenderStats | None = None,
                   index: Mapping[int, str] | None = None) -> RenderStats:
    """Bring one problem's folder on main in line with the registries."""
    stats = stats if stats is not None else RenderStats()
    pid = int(item["id"])
    folder = target_folder(item, index)
    if os.path.abspath(folder).startswith(os.path.abspath(paths.RECOMMENDED_DIR) + os.sep):
        print(f"[SKIP] oj{pid}: refusing to write into recommended/", file=sys.stderr)
        return stats

    if os.path.isdir(folder):
        desired = status_folder(item, folder)
        if desired != folder and not os.path.exists(desired):
            folder = sync_folder_status(item, folder)
            stats.folders_renamed += 1
        elif desired != folder:
            sync_folder_status(item, folder)  # reports the refusal
    else:
        fsio.ensure_dir(folder)
        stats.folders_created += 1

    md_path = os.path.join(folder, "problem.md")
    if detail is None:
        stats.no_detail.append(pid)
    else:
        fresh = render_problem_md(detail, item)
        current = _read(md_path)
        if current is not None and not is_generated_md(current):
            stats.handwritten_skipped.append(pid)
        elif current != fresh:
            fsio.write_text(md_path, fresh)
            stats.problem_md_written += 1

    _render_main_py(item, detail, folder, seed_code, stats)
    return stats


def render_ids(
    ids: Iterable[int] | None = None,
    *,
    seed_code: bool = False,
    summaries: Mapping[int, Mapping[str, Any]] | None = None,
    details: Mapping[int, Mapping[str, Any]] | None = None,
) -> RenderStats:
    """Render the given problem ids (default: every summary record).

    The registries are read from data/ unless passed in; the scraper passes
    its in-memory copies so a --dry-run scrape previews the fetched data.
    """
    summaries = summaries if summaries is not None else load_registry(paths.SUMMARY_JSON)
    details = details if details is not None else load_registry(paths.DETAIL_JSON)
    wanted = sorted(summaries) if ids is None else sorted(set(ids))

    stats = RenderStats()
    index = paths.index_problem_dirs()
    for pid in wanted:
        item = summaries.get(pid) or details.get(pid)
        if item is None:
            print(f"[WARN] oj{pid}: not in the registries, skipped", file=sys.stderr)
            continue
        render_problem(item, details.get(pid), seed_code=seed_code, stats=stats, index=index)
    return stats


def parse_ids(raw: str) -> set[int]:
    """Parse an id selection such as '3226,3290-3301'. Raises ValueError."""
    ids: set[int] = set()
    for token in raw.split(","):
        token = token.strip()
        if not token:
            continue
        if "-" in token:
            start, end = token.split("-", 1)
            ids.update(range(int(start), int(end) + 1))
        else:
            ids.add(int(token))
    return ids
